## One-Hot Encoding

In [ ]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()

ohe.fit_transform(np.array(['Male', 'Female']).reshape(-1, 1)).toarray()

array([[0., 1.],
       [1., 0.]])

In [ ]:
ohe.categories_

[array(['Female', 'Male'], dtype='<U6')]

In [ ]:
results = ohe.transform(np.array(['Female', 'Male', 'Male', 'Female']).reshape(-1, 1)).toarray()
print(results)

[[1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]]


## Label Encoding

In [ ]:
import numpy as np
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

le.fit(['Male', 'Female'])

LabelEncoder()

In [ ]:
le.classes_

array(['Female', 'Male'], dtype='<U6')

In [ ]:
results = le.transform(np.array(['Female', 'Male', 'Male', 'Female']))
print(results)

[0 1 1 0]
